# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "parallel_tests"

gem "cucumber"

gem "selenium-cucumber"

# gem "rails"
